# Generated by Django 5.2.18 on 2026-10-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('changed_mind', 'I changed my mind'), ('ordered_by_mistake', 'I ordered by mistake'), ('delivery_time', 'Delivery is taking too long'), ('price_changed', 'I found a better price'), ('other', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
